internal wrapper list for gosnappi helper Items()
open-traffic-generator/openapiart pull request #234
Opened 2021-11-02 14:45 UTC by alakendu

This should address https://github.com/open-traffic-generator/openapiart/issues/230

We will incorporate another internal variable within our wrapper package. We will fill that variable when access Items(). So it will not process each time. 
```go
type metricsResponse struct {
	obj          *snappipb.MetricsResponse
	portMetrics  []PortMetric
	flowMetrics  []FlowMetric
	bgpv4Metrics []Bgpv4Metric
	bgpv6Metrics []Bgpv6Metric
	isisMetrics  []IsisMetric
}

func (obj *metricsResponsePortMetricIter) Items() []PortMetric {
	if len(obj.obj.portMetrics) != len(obj.obj.obj.PortMetrics) {
		obj.obj.portMetrics = []PortMetric{}
		for _, item := range obj.obj.obj.PortMetrics {
			obj.obj.portMetrics = append(obj.obj.portMetrics, &portMetric{obj: item})
		}
	}
	return obj.obj.portMetrics
}
```

2021-11-04 15:16 UTC, ajbalogh reviewed
There is no validation test case that supports the change.

2021-11-08 15:58 UTC, alakendu commented
I think these UT indirectly covered those scenario:
```go
func TestIterAdd(t *testing.T) {
	api := openapiart.NewApi()
	config := api.NewPrefixConfig()
	config.G().Add()
	config.G().Add()
	assert.Equal(t, len(config.G().Items()), 2)
}

func TestIterAppend(t *testing.T) {
	api := openapiart.NewApi()
	config := api.NewPrefixConfig()
	config.G().Add()
	g := config.G().Append(openapiart.NewGObject())

	assert.Equal(t, len(g.Items()), 2)
}

func TestIterSet(t *testing.T) {
	api := openapiart.NewApi()
	config := api.NewPrefixConfig()
	name := "new name set on slice"
	config.G().Add().SetName("original name set on add")
	config.G().Add()
	g := config.G().Set(1, openapiart.NewGObject().SetName(name))

	assert.Equal(t, name, g.Items()[1].Name())
}
```

2021-11-09 07:42 UTC, ashutshkumr requested changes
I see following snippet for `Items()`:

```go
func (obj *prefixConfigGObjectIter) Items() []GObject {
	if len(obj.obj.gObjects) != len(obj.obj.obj.G) {
		obj.obj.gObjects = []GObject{}
		for _, item := range obj.obj.obj.G {
			obj.obj.gObjects = append(obj.obj.gObjects, &gObject{obj: item})
		}
	}
	return obj.obj.gObjects
}
```

But nothing seems to have changed for `Add()` or `Append()` or `Set()`. What this means is `Items()` MUST up processing entire list every time the list is modified.

e.g. If somebody does a `Set()`, it does not change the length of the items, so `Items()` will return items that were cached previously.

Hence, here's what I think needs to be done:
- Wrapper list should point to each item in the internal list, but this should not be done as part of `Items()`
- `Items()` should only return wrapper list
- `Add()` and `Append()` should modify both wrapper and internal list (ensuring the both point to same newly added object)
- `Set()` might need to modify both wrapper and internal list as well, but I think it will be done a little differently

Regarding unit test, noting down some of the missing coverage:
- Set index 1 of list with 3 items, and ensure we get the same item upon `Items()`
- Set index n of list where n is invalid index
- When doing Add/Append, don't just check the length of list, also validate the contents

2021-11-09 07:45 UTC, ashutshkumr commented
FYI, this is what I'm seeing in the generated code:

```go
func (obj *prefixConfigGObjectIter) Items() []GObject {
	if len(obj.obj.gObjects) != len(obj.obj.obj.G) {
		obj.obj.gObjects = []GObject{}
		for _, item := range obj.obj.obj.G {
			obj.obj.gObjects = append(obj.obj.gObjects, &gObject{obj: item})
		}
	}
	return obj.obj.gObjects
}

func (obj *prefixConfigGObjectIter) Add() GObject {
	newObj := &sanity.GObject{}
	obj.obj.obj.G = append(obj.obj.obj.G, newObj)
	newLibObj := &gObject{obj: newObj}
	newLibObj.setDefault()
	return newLibObj
}

func (obj *prefixConfigGObjectIter) Append(newObj GObject) PrefixConfigGObjectIter {
	obj.obj.obj.G = append(obj.obj.obj.G, newObj.Msg())
	return obj
}

func (obj *prefixConfigGObjectIter) Set(index int, newObj GObject) PrefixConfigGObjectIter {
	obj.obj.obj.G[index] = newObj.Msg()
	return obj
}
```

2021-11-09 13:22 UTC, alakendu commented
Update UT accordingly

2021-11-12 07:59 UTC, ashutshkumr commented
Why do we enclose this block inside `set_defaults` flag (the snippet is form validateObj) ? We should initialize wrapper list regardless of whether set_default is true or false, right ?

```go
		if set_default {
			obj.gObjects = []GObject{}
			for _, item := range obj.obj.G {
				obj.gObjects = append(obj.gObjects, &gObject{obj: item})
			}
		}
```

2021-11-12 11:28 UTC, merged