Auto Model fix
open-traffic-generator/openapiart pull request #306
Opened 2022-02-08 07:31 UTC by Rangababu-R

2022-02-08 15:16 UTC, ajbalogh requested changes
The changes LGTM but please add a specific test for this auto case.
The test should confirm that the following has been generated when auto is present: description, type,  default etc...

2022-02-09 07:22 UTC, Rangababu-R commented
> The changes LGTM but please add a specific test for this auto case. The test should confirm that the following has been generated when auto is present: description, type, default etc...

@ajbalogh, Added unit tests that would validate the auto feature.

2022-02-09 15:15 UTC, ajbalogh approved these changes

2022-02-10 06:39 UTC, ANISH-GOTTAPU approved these changes

2022-02-11 07:08 UTC, merged