Add support for external grpc client
open-traffic-generator/openapiart pull request #329
Opened 2022-05-17 10:02 UTC by alakendu

resolves https://github.com/open-traffic-generator/openapiart/issues/328

We will expose these two methods in GrpcTransport interface
```go
	// SetClientConnection set grpc DialContext
	SetClientConnection(con *grpc.ClientConn) GrpcTransport
	// ClientConnection get grpc DialContext
	ClientConnection() *grpc.ClientConn
```
This is one snippet how user call it

```go
	ctx, cancelFunc := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancelFunc()
	conn, err := grpc.DialContext(ctx, grpcServer.Location, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatal(fmt.Sprintf("failed grpc dialcontext due to %s", err.Error()))
	}
	clientConnApi := openapiart.NewApi()
	clientConnApi.NewGrpcTransport().SetClientConnection(conn)
```

2022-05-17 14:26 UTC, ajbalogh requested changes
lgtm except for minor indenting

2022-05-17 14:26 UTC, ajbalogh commented on openapiart/common.go
> +    // SetLocation set client connection to the given grpc target
minor nit, fix indenting on this line and other comments in this interface

2022-05-17 15:03 UTC, ajbalogh approved these changes

2022-05-18 20:01 UTC, alexmasi commented
Anything stopping this from being merged?

2022-05-18 20:22 UTC, ajbalogh commented
@alexmasi the change looks good but its missing a unit test which will be addressed asap.

2022-05-18 20:22 UTC, ajbalogh requested changes
Missing a unit test.

2022-05-19 10:24 UTC, alakendu commented
I have created another api  `clientConnApi`  using SetClientConnection() which will use at the time of other UT execution. 
But I agree it will better to add additional UT. Please check this UT `TestGrpcClientConnection`
https://github.com/open-traffic-generator/openapiart/blob/main/pkg/transport_test.go

2022-05-19 14:46 UTC, ajbalogh approved these changes

2022-05-19 14:47 UTC, merged