Need to maintain consistent .proto message field numbers
open-traffic-generator/openapiart pull request #355
Opened 2022-07-28 10:28 UTC by alakendu

2022-08-02 08:00 UTC, Rangababu-R requested changes

2022-08-02 08:06 UTC, Rangababu-R commented
Can't the enum be below format? why do we need to add x-enum?
```yaml
enum:
  - status_200:
    x-field-uid: 1
  - status_400:
    x-field-uid: 2
  - status_404:
    x-field-uid: 3
  - status_500:
    x-field-uid: 4
```

2022-08-02 11:06 UTC, alakendu commented on openapiart/openapiartprotobuf.py
> +            reserved_field_uids = schema_object["x-reserved-field-uids"]
done

2022-08-02 11:06 UTC, alakendu commented on openapiart/openapiartprotobuf.py
> +    def _check_duplicate_uid(self, fields_uid, name):
done

2022-08-02 11:07 UTC, alakendu commented on openapiart/openapiartprotobuf.py
> +            if "x-field-uid" not in value:
done

2022-08-02 12:29 UTC, alakendu commented on utils/autofielduid.py
> +import os
ok

2022-08-02 16:09 UTC, alakendu commented on openapiart/bundler.py
> +                if property_object["type"] == "string":
I think our latest opeanapiart are covering only for string. Please let me know if I have missed something.

2022-08-02 16:12 UTC, alakendu commented on openapiart/bundler.py
> +                            "x-include should be part of properties and responses for %s"
modify it

2022-08-02 17:50 UTC, alakendu commented on openapiart/bundler.py
> +                        obj_path = "/".join(paths[:4])
done

2022-08-02 17:50 UTC, alakendu commented on openapiart/bundler.py
> +                        for node in paths[4:]:
done

2022-08-11 18:24 UTC, ankur-sheth commented
I'm not the right person to review this.  As long as the team has reviewed it, I'm ok.

2022-08-16 14:19 UTC, ashutshkumr approved these changes

2022-08-16 14:20 UTC, merged