Segregate proto generation
open-traffic-generator/openapiart pull request #386
Opened 2023-01-13 13:46 UTC by Vibaswan

2023-01-13 13:51 UTC, Vibaswan commented
For some reason not sure why Ranga actually made the change which i am reverting right now
https://github.com/open-traffic-generator/openapiart/commit/8fc7b8d1e559dcf9f759cb67bf277fd4531ef065#diff-c4e7b5e541655c6a631951b4e8fe368a052b0132fe605d13fbad12689fb0c416

But I don't see any problem in keeping it separate.

2023-01-24 10:05 UTC, Vibaswan commented
Made changes in CI so that generated proto, yml and json is validated

2023-01-27 14:09 UTC, ashutshkumr requested changes
Please also sync with main

2023-01-27 14:09 UTC, ashutshkumr commented on openapiart/openapiart.py
> +        self._generate_proto_file()
We should not generate proto by default (as some environments may not have such requirements).

I recommend exposing a func for generating protobuf separately.
```python
art.GenerateProtoDef(
    package_name="sanity"
)
```

Moreover, I would recommend performing `_generate_proto_file` durin both python and Go SDK (if it hasn't already been performed)

2023-01-27 14:49 UTC, ashutshkumr approved these changes

2023-01-27 14:59 UTC, merged