Enable logging support in python sdk#347
open-traffic-generator/openapiart pull request #403
Opened 2023-02-27 11:57 UTC by dipendughosh

Enabled logging in python sdk. The framework support for logging is enabled. Need to add more logging as and when needed.

2023-02-28 06:20 UTC, Vibaswan requested changes

2023-02-28 06:20 UTC, Vibaswan commented on openapiart/common.py
> +    module="common",
Where is the module being used ?

2023-02-28 06:20 UTC, Vibaswan commented on openapiart/common.py
> +        log.info(
should be a debug I guess

2023-03-02 09:18 UTC, dipendughosh commented on openapiart/common.py
> +log = logging.Logger("common", level=logging.WARN)
done

2023-03-02 09:18 UTC, dipendughosh commented on openapiart/common.py
> +    module="common",
done

2023-03-02 09:19 UTC, dipendughosh commented on openapiart/common.py
> +        log.info("Logger already instantiated ")
done

2023-03-02 09:26 UTC, dipendughosh commented on openapiart/common.py
> +        log.warning("Serializeing data - " + str(data))
done

2023-03-02 09:26 UTC, dipendughosh commented on openapiart/common.py
> +        log.warning("Deserializeing")
done

2023-03-02 09:27 UTC, dipendughosh commented on openapiart/common.py
> +            log.debug("Validating MAC address - " + str(mac))
done

2023-03-02 09:28 UTC, dipendughosh commented on openapiart/common.py
> +            log.debug("Validating IPv4 address - " + str(ip))
done

2023-03-02 09:29 UTC, dipendughosh commented on openapiart/common.py
> +            log.debug("Validating IPv6 address - " + str(ip))
done

2023-03-02 09:36 UTC, dipendughosh commented on openapiart/common.py
> +        log.debug(
DONE

2023-03-02 09:37 UTC, dipendughosh commented on openapiart/common.py
> +        log.info(
done

2023-03-02 09:38 UTC, dipendughosh commented on openapiart/common.py
> +        log.debug("Get name - " + str(name))
done

2023-03-06 04:25 UTC, Vibaswan approved these changes

2023-05-05 11:26 UTC, closed without merging